name: Update example games

on:
  workflow_dispatch:
    inputs:
      version:
        description: "SDK Version"

jobs:
  updateExamples:
    runs-on: ubuntu-latest
    steps:
      - name: Configuring git user
        run: |
          git config --global user.name "rune-ci"
          git config --global user.email "ci@rune.ai"

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install
      - run: |
          yarn updateExampleGames ${{ github.event.inputs.version }}
          git commit -am "Update example games to SDK version ${{ github.event.inputs.version }}"
          git push
